package ee.schimke.m3catalog

import java.io.File

/**
 * Renders `CatalogMatrixAnnotations.kt` from [CatalogMatrixDeclarations].
 *
 * `CatalogVariantMatrix.expand()` already produces the exact set of cells each matrix should carry
 * — names and seeds both, including the `namesEveryValue` rule and the skip-the-all-defaults-cell
 * rule. Writing those same cells out by hand as `@OverrideVariant` annotations made two artifacts
 * for one fact, and left "add a size to `CatalogSize`" meaning "hand-type thirty new lines into
 * `IconButtonMatrix` in the right order with the right default-elision" (#107).
 *
 * Kotlin annotation arguments must be compile-time constants, so a matrix computed at runtime
 * cannot *be* an `@OverrideVariant` block. What it can do is write one: this generator emits the
 * file, the output is committed like any other source, and `CatalogMatrixAnnotationsTest` asserts
 * the committed copy is exactly what the declarations produce. The same regenerate-and-diff shape
 * the `design-map` job already uses for `design-map.json`, with the comparison moved into the unit
 * tests so it costs no extra CI job.
 *
 * Run it with `./gradlew :catalog:generateMatrixAnnotations`.
 *
 * The emitted formatting is ktfmt's (google style, 100 columns): an annotation that fits on one
 * line stays on one, a longer one breaks one argument per line with a trailing comma, and KDoc
 * paragraphs are greedy-wrapped to the same width. That is what keeps `ktfmtCheck` and this
 * generator from disagreeing about the same file.
 */
object MatrixAnnotationsGenerator {

  private const val MAX_WIDTH = 100

  /** The prose header the generated file opens with, above the first annotation. */
  private val HEADER =
    """
    //
    // GENERATED by `./gradlew :catalog:generateMatrixAnnotations` from `CatalogMatrixDeclarations`
    // — edit those declarations (and the axes in `CatalogAxes.kt` they expand), never this file.
    //
    // The catalog's variant matrices, declared **once each** as annotations rather than retyped per
    // component.
    //
    // A matrix is a cross product — five sizes by two shapes, or by three widths as well — and every
    // component of a family carries the identical set of cells. Written out per component that was 250
    // `@OverrideVariant` annotations across thirteen blocks: the same cell spelled out five times for
    // the buttons, four for the icon buttons, twice for each toggle default. Nothing kept the copies in
    // step, and they had already drifted (`IconButtons.kt` spelled the default size explicitly in
    // `s-narrow` and implicitly in `s-square`).
    //
    // `@OverrideVariant` targets `ANNOTATION_CLASS` as of compose-ai-tools 0.19.50, so a matrix can be
    // declared here and applied with one line. The cells are exactly what `CatalogVariantMatrix.expand`
    // produces, so the axes in `CatalogAxes.kt` are the only place a cell is authored.
    //
    // Note that stacking two of these would **union** their cells, not multiply them: each annotation
    // is a finished matrix, not an axis. A component needing a genuine extra dimension wants a
    // different matrix declared here, not two of these together.
    //
    // The interaction-state annotations are hand-authored and live in
    // `CatalogInteractionAnnotations.kt`: they seed no axis, so they are not a cross product.
    //
    """
      .trimIndent()

  /** The whole file, as text. */
  fun render(declarations: List<CatalogMatrixDeclaration> = CatalogMatrixDeclarations): String =
    buildString {
      appendLine("package ee.schimke.m3catalog")
      appendLine()
      appendLine("import ee.schimke.composeai.preview.OverrideVariant")
      appendLine()
      appendLine(HEADER)
      for (declaration in declarations) {
        appendLine()
        append(kdoc(declaration.doc))
        for (cell in declaration.matrix.cells) append(annotation(cell))
        appendLine("annotation class ${declaration.annotation}")
      }
    }

  /** One `@OverrideVariant(...)`, on one line where it fits and one argument per line where not. */
  private fun annotation(cell: CatalogVariantCell): String {
    val arguments = buildList {
      add("name = ${cell.name.quoted()}")
      if (cell.booleans.isNotEmpty()) add("booleans = ${cell.booleans.asSeedArray()}")
      if (cell.strings.isNotEmpty()) add("strings = ${cell.strings.asSeedArray()}")
    }
    val oneLine = "@OverrideVariant(${arguments.joinToString(", ")})"
    if (oneLine.length <= MAX_WIDTH) return oneLine + "\n"
    return buildString {
      appendLine("@OverrideVariant(")
      arguments.forEach { appendLine("  $it,") }
      appendLine(")")
    }
  }

  /** `key = value` seeds as the `["key=value", …]` array an `@OverrideVariant` takes. */
  private fun Map<String, String>.asSeedArray(): String =
    entries.joinToString(", ", "[", "]") { "$it".quoted() }

  private fun String.quoted() = "\"$this\""

  /** The declaration's prose as KDoc: one line where it fits, greedy-wrapped to [MAX_WIDTH]. */
  private fun kdoc(doc: String): String {
    val paragraphs = doc.trimIndent().trim().split(Regex("\n\\s*\n")).map { it.replace("\n", " ") }
    if (paragraphs.size == 1) {
      val single = "/** ${paragraphs.first()} */"
      if (single.length <= MAX_WIDTH) return single + "\n"
    }
    return buildString {
      appendLine("/**")
      paragraphs.forEachIndexed { index, paragraph ->
        if (index > 0) appendLine(" *")
        wrap(paragraph).forEach { appendLine(" * $it") }
      }
      appendLine(" */")
    }
  }

  /** Greedy fill: as many words per line as fit inside [MAX_WIDTH] once ` * ` is prefixed. */
  private fun wrap(paragraph: String): List<String> {
    val lines = mutableListOf<String>()
    var line = StringBuilder()
    for (word in paragraph.split(" ").filter { it.isNotEmpty() }) {
      when {
        line.isEmpty() -> line.append(word)
        line.length + 1 + word.length + 3 <= MAX_WIDTH -> line.append(' ').append(word)
        else -> {
          lines.add(line.toString())
          line = StringBuilder(word)
        }
      }
    }
    if (line.isNotEmpty()) lines.add(line.toString())
    return lines
  }
}

/** Writes the generated file to the path given as the single argument. */
fun main(args: Array<String>) {
  val target = File(args.single())
  target.writeText(MatrixAnnotationsGenerator.render())
  println("wrote ${target.path}")
}
