// GENERATED by scripts/samples-previews.mjs — do not edit.
//
// A `@Preview` wrapper for every vendored foundation sample that does not carry one upstream. Only
// 7 of the 73 sample files in `androidx.compose.foundation.samples` and
// `androidx.compose.foundation.layout.samples` are annotated, so without these the catalog would
// publish a tenth of the corpus. `:samples-catalog` needs no equivalent: 298 of its 317 material3
// samples are already annotated.
//
// The wrappers live HERE, in this module's own package, and never inside `upstream/` — that tree is
// upstream's bytes and is re-fetched byte-identically on every import.

package ee.schimke.uisamplescatalog

import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview

@Preview
@Composable
fun AbsoluteOffsetModifierPreview() = androidx.compose.foundation.layout.samples.AbsoluteOffsetModifier()

@Preview
@Composable
fun AbsoluteOffsetPxModifierPreview() = androidx.compose.foundation.layout.samples.AbsoluteOffsetPxModifier()

@Preview
@Composable
fun AbsolutePaddingModifierPreview() = androidx.compose.foundation.layout.samples.AbsolutePaddingModifier()

@Preview
@Composable
fun AnchoredDraggableDynamicAnchorsSamplePreview() = androidx.compose.foundation.samples.AnchoredDraggableDynamicAnchorsSample()

@Preview
@Composable
fun AnimateItemSamplePreview() = androidx.compose.foundation.samples.AnimateItemSample()

@Preview
@Composable
fun AnimateScrollPageSamplePreview() = androidx.compose.foundation.samples.AnimateScrollPageSample()

@Preview
@Composable
fun AwaitDragOrCancellationSamplePreview() = androidx.compose.foundation.samples.AwaitDragOrCancellationSample()

@Preview
@Composable
fun AwaitHorizontalDragOrCancellationSamplePreview() = androidx.compose.foundation.samples.AwaitHorizontalDragOrCancellationSample()

@Preview
@Composable
fun AwaitLongPressOrCancellationSamplePreview() = androidx.compose.foundation.samples.AwaitLongPressOrCancellationSample()

@Preview
@Composable
fun AwaitVerticalDragOrCancellationSamplePreview() = androidx.compose.foundation.samples.AwaitVerticalDragOrCancellationSample()

@Preview
@Composable
fun BasicLoginFormSamplePreview() = androidx.compose.foundation.samples.BasicLoginFormSample()

@Preview
@Composable
fun BasicTextFieldAnnotatedOutputTransformationSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldAnnotatedOutputTransformationSample()

@Preview
@Composable
fun BasicTextFieldChangeIterationSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldChangeIterationSample()

@Preview
@Composable
fun BasicTextFieldChangeReverseIterationSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldChangeReverseIterationSample()

@Preview
@Composable
fun BasicTextFieldCustomInputTransformationSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldCustomInputTransformationSample()

@Preview
@Composable
fun BasicTextFieldDecoratorSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldDecoratorSample()

@Preview
@Composable
fun BasicTextFieldInputTransformationByValueChooseSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldInputTransformationByValueChooseSample()

@Preview
@Composable
fun BasicTextFieldInputTransformationByValueReplaceSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldInputTransformationByValueReplaceSample()

@Preview
@Composable
fun BasicTextFieldInputTransformationMaxLengthCustomPreview() = androidx.compose.foundation.samples.BasicTextFieldInputTransformationMaxLengthCustom()

@Preview
@Composable
fun BasicTextFieldOutputTransformationSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldOutputTransformationSample()

@Preview
@Composable
fun BasicTextFieldSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldSample()

@Preview
@Composable
fun BasicTextFieldTrackedRangePropertiesSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldTrackedRangePropertiesSample()

@Preview
@Composable
fun BasicTextFieldTrackedRangeSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldTrackedRangeSample()

@Preview
@Composable
fun BasicTextFieldTrackedRangeTextRangeSetterSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldTrackedRangeTextRangeSetterSample()

@Preview
@Composable
fun BasicTextFieldTrackedRangeToggleBoldSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldTrackedRangeToggleBoldSample()

@Preview
@Composable
fun BasicTextFieldUndoSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldUndoSample()

@Preview
@Composable
fun BasicTextFieldWithStringSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldWithStringSample()

@Preview
@Composable
fun BasicTextFieldWithValueOnValueChangeSamplePreview() = androidx.compose.foundation.samples.BasicTextFieldWithValueOnValueChangeSample()

@Preview
@Composable
fun BitmapPainterSamplePreview() = androidx.compose.foundation.samples.BitmapPainterSample()

@Preview
@Composable
fun BitmapPainterSubsectionSamplePreview() = androidx.compose.foundation.samples.BitmapPainterSubsectionSample()

@Preview
@Composable
fun BorderSamplePreview() = androidx.compose.foundation.samples.BorderSample()

@Preview
@Composable
fun BorderSampleWithBrushPreview() = androidx.compose.foundation.samples.BorderSampleWithBrush()

@Preview
@Composable
fun BorderSampleWithDataClassPreview() = androidx.compose.foundation.samples.BorderSampleWithDataClass()

@Preview
@Composable
fun BorderSampleWithDynamicDataPreview() = androidx.compose.foundation.samples.BorderSampleWithDynamicData()

@Preview
@Composable
fun BoxWithConstraintsSamplePreview() = androidx.compose.foundation.layout.samples.BoxWithConstraintsSample()

@Preview
@Composable
fun BringIntoViewSamplePreview() = androidx.compose.foundation.samples.BringIntoViewSample()

@Preview
@Composable
fun BringPartOfComposableIntoViewSamplePreview() = androidx.compose.foundation.samples.BringPartOfComposableIntoViewSample()

@Preview
@Composable
fun CalculateCentroidSizePreview() = androidx.compose.foundation.samples.CalculateCentroidSize()

@Preview
@Composable
fun CalculatePanPreview() = androidx.compose.foundation.samples.CalculatePan()

@Preview
@Composable
fun CalculateRotationPreview() = androidx.compose.foundation.samples.CalculateRotation()

@Preview
@Composable
fun CalculateZoomPreview() = androidx.compose.foundation.samples.CalculateZoom()

@Preview
@Composable
fun CanScrollSamplePreview() = androidx.compose.foundation.samples.CanScrollSample()

@Preview
@Composable
fun CanvasPieChartSamplePreview() = androidx.compose.foundation.samples.CanvasPieChartSample()

@Preview
@Composable
fun CanvasSamplePreview() = androidx.compose.foundation.samples.CanvasSample()

@Preview
@Composable
fun CheckoutRegisterFormSamplePreview() = androidx.compose.foundation.samples.CheckoutRegisterFormSample()

@Preview
@Composable
fun ClickableSamplePreview() = androidx.compose.foundation.samples.ClickableSample()

@Preview
@Composable
fun ContextualFlowColMaxLineDynamicSeeMorePreview() = androidx.compose.foundation.layout.samples.ContextualFlowColMaxLineDynamicSeeMore()

@Preview
@Composable
fun ContextualFlowColumn_ItemPositionPreview() = androidx.compose.foundation.layout.samples.ContextualFlowColumn_ItemPosition()

@Preview
@Composable
fun ContextualFlowRow_ItemPositionPreview() = androidx.compose.foundation.layout.samples.ContextualFlowRow_ItemPosition()

@Preview
@Composable
fun ContextualFlowRowMaxLineDynamicSeeMorePreview() = androidx.compose.foundation.layout.samples.ContextualFlowRowMaxLineDynamicSeeMore()

@Preview
@Composable
fun ControlledScrollableRowSamplePreview() = androidx.compose.foundation.samples.ControlledScrollableRowSample()

@Preview
@Composable
fun CreditCardSamplePreview() = androidx.compose.foundation.samples.CreditCardSample()

@Preview
@Composable
fun CustomPageSizeSamplePreview() = androidx.compose.foundation.samples.CustomPageSizeSample()

@Preview
@Composable
fun DarkThemeSamplePreview() = androidx.compose.foundation.samples.DarkThemeSample()

@Preview
@Composable
fun DateTimeSchedulerFormSamplePreview() = androidx.compose.foundation.samples.DateTimeSchedulerFormSample()

@Preview
@Composable
fun DecimalInputSamplePreview() = androidx.compose.foundation.samples.DecimalInputSample()

@Preview
@Composable
fun DefaultMinSizeSamplePreview() = androidx.compose.foundation.layout.samples.DefaultMinSizeSample()

@Preview
@Composable
fun DetectDragGesturesSamplePreview() = androidx.compose.foundation.samples.DetectDragGesturesSample()

@Preview
@Composable
fun DetectDragWithLongPressGesturesSamplePreview() = androidx.compose.foundation.samples.DetectDragWithLongPressGesturesSample()

@Preview
@Composable
fun DetectHorizontalDragGesturesSamplePreview() = androidx.compose.foundation.samples.DetectHorizontalDragGesturesSample()

@Preview
@Composable
fun DetectTransformGesturesPreview() = androidx.compose.foundation.samples.DetectTransformGestures()

@Preview
@Composable
fun DetectVerticalDragGesturesSamplePreview() = androidx.compose.foundation.samples.DetectVerticalDragGesturesSample()

@Preview
@Composable
fun DeterminateProgressSemanticsSamplePreview() = androidx.compose.foundation.samples.DeterminateProgressSemanticsSample()

@Preview
@Composable
fun DisableSelectionSamplePreview() = androidx.compose.foundation.samples.DisableSelectionSample()

@Preview
@Composable
fun Draggable2DSamplePreview() = androidx.compose.foundation.samples.Draggable2DSample()

@Preview
@Composable
fun DraggableSamplePreview() = androidx.compose.foundation.samples.DraggableSample()

@Preview
@Composable
fun DragSamplePreview() = androidx.compose.foundation.samples.DragSample()

@Preview
@Composable
fun DrawBackgroundColorPreview() = androidx.compose.foundation.samples.DrawBackgroundColor()

@Preview
@Composable
fun DrawBackgroundShapedBrushPreview() = androidx.compose.foundation.samples.DrawBackgroundShapedBrush()

@Preview
@Composable
fun ExtendSelectionSamplePreview() = androidx.compose.foundation.samples.ExtendSelectionSample()

@Preview
@Composable
fun FillHalfHeightModifierPreview() = androidx.compose.foundation.layout.samples.FillHalfHeightModifier()

@Preview
@Composable
fun FillHalfSizeModifierPreview() = androidx.compose.foundation.layout.samples.FillHalfSizeModifier()

@Preview
@Composable
fun FillHalfWidthModifierPreview() = androidx.compose.foundation.layout.samples.FillHalfWidthModifier()

@Preview
@Composable
fun FitInsideOutsideExamplePreview() = androidx.compose.foundation.layout.samples.FitInsideOutsideExample()

@Preview
@Composable
fun FocusableFocusGroupSamplePreview() = androidx.compose.foundation.samples.FocusableFocusGroupSample()

@Preview
@Composable
fun FocusableSamplePreview() = androidx.compose.foundation.samples.FocusableSample()

@Preview
@Composable
fun FocusGroupSamplePreview() = androidx.compose.foundation.samples.FocusGroupSample()

@Preview
@Composable
fun FocusScrollingInLazyRowSamplePreview() = androidx.compose.foundation.samples.FocusScrollingInLazyRowSample()

@Preview
@Composable
fun GridConfigurationDslSamplePreview() = androidx.compose.foundation.layout.samples.GridConfigurationDslSample()

@Preview
@Composable
fun GridWithAreaRangesPreview() = androidx.compose.foundation.layout.samples.GridWithAreaRanges()

@Preview
@Composable
fun GridWithAutoPlacementPreview() = androidx.compose.foundation.layout.samples.GridWithAutoPlacement()

@Preview
@Composable
fun GridWithConstraintsPreview() = androidx.compose.foundation.layout.samples.GridWithConstraints()

@Preview
@Composable
fun GridWithLazyListPreview() = androidx.compose.foundation.layout.samples.GridWithLazyList()

@Preview
@Composable
fun GridWithNamedAreasPreview() = androidx.compose.foundation.layout.samples.GridWithNamedAreas()

@Preview
@Composable
fun GridWithOneDimensionalAreasPreview() = androidx.compose.foundation.layout.samples.GridWithOneDimensionalAreas()

@Preview
@Composable
fun GridWithSpanningItemsPreview() = androidx.compose.foundation.layout.samples.GridWithSpanningItems()

@Preview
@Composable
fun HorizontalDragSamplePreview() = androidx.compose.foundation.samples.HorizontalDragSample()

@Preview
@Composable
fun HorizontalPagerWithScrollableContentPreview() = androidx.compose.foundation.samples.HorizontalPagerWithScrollableContent()

@Preview
@Composable
fun HorizontalScrollSamplePreview() = androidx.compose.foundation.samples.HorizontalScrollSample()

@Preview
@Composable
fun HoverableSamplePreview() = androidx.compose.foundation.samples.HoverableSample()

@Preview
@Composable
fun ImageSamplePreview() = androidx.compose.foundation.samples.ImageSample()

@Preview
@Composable
fun IndeterminateProgressSemanticsSamplePreview() = androidx.compose.foundation.samples.IndeterminateProgressSemanticsSample()

@Preview
@Composable
fun IndicationSamplePreview() = androidx.compose.foundation.samples.IndicationSample()

@Preview
@Composable
fun InlineTextContentSamplePreview() = androidx.compose.foundation.samples.InlineTextContentSample()

@Preview
@Composable
fun InteractionSourceFlowSamplePreview() = androidx.compose.foundation.samples.InteractionSourceFlowSample()

@Preview
@Composable
fun ItemCountSettingsSamplePreview() = androidx.compose.foundation.samples.ItemCountSettingsSample()

@Preview
@Composable
fun LazyColumnSamplePreview() = androidx.compose.foundation.samples.LazyColumnSample()

@Preview
@Composable
fun LazyLayoutItemProviderSamplePreview() = androidx.compose.foundation.samples.LazyLayoutItemProviderSample()

@Preview
@Composable
fun LazyRowSamplePreview() = androidx.compose.foundation.samples.LazyRowSample()

@Preview
@Composable
fun MatchParentDividerForAspectRatioPreview() = androidx.compose.foundation.layout.samples.MatchParentDividerForAspectRatio()

@Preview
@Composable
fun MatchParentDividerForTextPreview() = androidx.compose.foundation.layout.samples.MatchParentDividerForText()

@Preview
@Composable
fun ObservingStateChangesInPagerStateSamplePreview() = androidx.compose.foundation.samples.ObservingStateChangesInPagerStateSample()

@Preview
@Composable
fun OffsetModifierPreview() = androidx.compose.foundation.layout.samples.OffsetModifier()

@Preview
@Composable
fun OffsetPxModifierPreview() = androidx.compose.foundation.layout.samples.OffsetPxModifier()

@Preview
@Composable
fun OverscrollRenderedOnTopOfLazyListDecorationsPreview() = androidx.compose.foundation.samples.OverscrollRenderedOnTopOfLazyListDecorations()

@Preview
@Composable
fun OverscrollSamplePreview() = androidx.compose.foundation.samples.OverscrollSample()

@Preview
@Composable
fun OverscrollWithDraggable_AfterPreview() = androidx.compose.foundation.samples.OverscrollWithDraggable_After()

@Preview
@Composable
fun OverscrollWithDraggable_BeforePreview() = androidx.compose.foundation.samples.OverscrollWithDraggable_Before()

@Preview
@Composable
fun PaddingAllModifierPreview() = androidx.compose.foundation.layout.samples.PaddingAllModifier()

@Preview
@Composable
fun PaddingFromBaselineSampleDpPreview() = androidx.compose.foundation.layout.samples.PaddingFromBaselineSampleDp()

@Preview
@Composable
fun PaddingFromBaselineSampleTextUnitPreview() = androidx.compose.foundation.layout.samples.PaddingFromBaselineSampleTextUnit()

@Preview
@Composable
fun PaddingFromSamplePreview() = androidx.compose.foundation.layout.samples.PaddingFromSample()

@Preview
@Composable
fun PaddingModifierPreview() = androidx.compose.foundation.layout.samples.PaddingModifier()

@Preview
@Composable
fun PaddingValuesModifierPreview() = androidx.compose.foundation.layout.samples.PaddingValuesModifier()

@Preview
@Composable
fun PagerCustomAnimateScrollToPagePreview() = androidx.compose.foundation.samples.PagerCustomAnimateScrollToPage()

@Preview
@Composable
fun PagerWithStateSamplePreview() = androidx.compose.foundation.samples.PagerWithStateSample()

@Preview
@Composable
fun PinCodeEntryRowSamplePreview() = androidx.compose.foundation.samples.PinCodeEntryRowSample()

@Preview
@Composable
fun PlaceholderBasicTextFieldSamplePreview() = androidx.compose.foundation.samples.PlaceholderBasicTextFieldSample()

@Preview
@Composable
fun RegistrationFormSamplePreview() = androidx.compose.foundation.samples.RegistrationFormSample()

@Preview
@Composable
fun SameWidthBoxesPreview() = androidx.compose.foundation.layout.samples.SameWidthBoxes()

@Preview
@Composable
fun SameWidthTextBoxesPreview() = androidx.compose.foundation.layout.samples.SameWidthTextBoxes()

@Preview
@Composable
fun Scrollable2DSamplePreview() = androidx.compose.foundation.samples.Scrollable2DSample()

@Preview
@Composable
fun ScrollableAreaSamplePreview() = androidx.compose.foundation.samples.ScrollableAreaSample()

@Preview
@Composable
fun ScrollableSamplePreview() = androidx.compose.foundation.samples.ScrollableSample()

@Preview
@Composable
fun ScrollToPageSamplePreview() = androidx.compose.foundation.samples.ScrollToPageSample()

@Preview
@Composable
fun SelectableSamplePreview() = androidx.compose.foundation.samples.SelectableSample()

@Preview
@Composable
fun SelectAllSamplePreview() = androidx.compose.foundation.samples.SelectAllSample()

@Preview
@Composable
fun SelectionSamplePreview() = androidx.compose.foundation.samples.SelectionSample()

@Preview
@Composable
fun SelectionStateSamplePreview() = androidx.compose.foundation.samples.SelectionStateSample()

@Preview
@Composable
fun SelectQuerySamplePreview() = androidx.compose.foundation.samples.SelectQuerySample()

@Preview
@Composable
fun SelectThirdTextSamplePreview() = androidx.compose.foundation.samples.SelectThirdTextSample()

@Preview
@Composable
fun SimpleAlignByInRowPreview() = androidx.compose.foundation.layout.samples.SimpleAlignByInRow()

@Preview
@Composable
fun SimpleAlignInColumnPreview() = androidx.compose.foundation.layout.samples.SimpleAlignInColumn()

@Preview
@Composable
fun SimpleAlignInRowPreview() = androidx.compose.foundation.layout.samples.SimpleAlignInRow()

@Preview
@Composable
fun SimpleAspectRatioPreview() = androidx.compose.foundation.layout.samples.SimpleAspectRatio()

@Preview
@Composable
fun SimpleBoxPreview() = androidx.compose.foundation.layout.samples.SimpleBox()

@Preview
@Composable
fun SimpleColumnPreview() = androidx.compose.foundation.layout.samples.SimpleColumn()

@Preview
@Composable
fun SimpleFillHeightModifierPreview() = androidx.compose.foundation.layout.samples.SimpleFillHeightModifier()

@Preview
@Composable
fun SimpleFillModifierPreview() = androidx.compose.foundation.layout.samples.SimpleFillModifier()

@Preview
@Composable
fun SimpleFillWidthModifierPreview() = androidx.compose.foundation.layout.samples.SimpleFillWidthModifier()

@Preview
@Composable
fun SimpleFlowColumnPreview() = androidx.compose.foundation.layout.samples.SimpleFlowColumn()

@Preview
@Composable
fun SimpleFlowColumn_EqualWidthPreview() = androidx.compose.foundation.layout.samples.SimpleFlowColumn_EqualWidth()

@Preview
@Composable
fun SimpleFlowColumnMaxLinesDynamicSeeMorePreview() = androidx.compose.foundation.layout.samples.SimpleFlowColumnMaxLinesDynamicSeeMore()

@Preview
@Composable
fun SimpleFlowColumnMaxLinesWithSeeMorePreview() = androidx.compose.foundation.layout.samples.SimpleFlowColumnMaxLinesWithSeeMore()

@Preview
@Composable
fun SimpleFlowRowPreview() = androidx.compose.foundation.layout.samples.SimpleFlowRow()

@Preview
@Composable
fun SimpleFlowRow_EqualHeightPreview() = androidx.compose.foundation.layout.samples.SimpleFlowRow_EqualHeight()

@Preview
@Composable
fun SimpleFlowRowMaxLinesDynamicSeeMorePreview() = androidx.compose.foundation.layout.samples.SimpleFlowRowMaxLinesDynamicSeeMore()

@Preview
@Composable
fun SimpleFlowRowMaxLinesWithSeeMorePreview() = androidx.compose.foundation.layout.samples.SimpleFlowRowMaxLinesWithSeeMore()

@Preview
@Composable
fun SimpleGridPreview() = androidx.compose.foundation.layout.samples.SimpleGrid()

@Preview
@Composable
fun SimpleHeightModifierPreview() = androidx.compose.foundation.layout.samples.SimpleHeightModifier()

@Preview
@Composable
fun SimpleHorizontalPagerSamplePreview() = androidx.compose.foundation.samples.SimpleHorizontalPagerSample()

@Preview
@Composable
fun SimpleInteractionSourceSamplePreview() = androidx.compose.foundation.samples.SimpleInteractionSourceSample()

@Preview
@Composable
fun SimpleRelativeToSiblingsPreview() = androidx.compose.foundation.layout.samples.SimpleRelativeToSiblings()

@Preview
@Composable
fun SimpleRelativeToSiblingsInColumnPreview() = androidx.compose.foundation.layout.samples.SimpleRelativeToSiblingsInColumn()

@Preview
@Composable
fun SimpleRequiredHeightModifierPreview() = androidx.compose.foundation.layout.samples.SimpleRequiredHeightModifier()

@Preview
@Composable
fun SimpleRequiredSizeModifierPreview() = androidx.compose.foundation.layout.samples.SimpleRequiredSizeModifier()

@Preview
@Composable
fun SimpleRequiredWidthModifierPreview() = androidx.compose.foundation.layout.samples.SimpleRequiredWidthModifier()

@Preview
@Composable
fun SimpleRowPreview() = androidx.compose.foundation.layout.samples.SimpleRow()

@Preview
@Composable
fun SimpleSizeModifierPreview() = androidx.compose.foundation.layout.samples.SimpleSizeModifier()

@Preview
@Composable
fun SimpleSizeModifierWithDpSizePreview() = androidx.compose.foundation.layout.samples.SimpleSizeModifierWithDpSize()

@Preview
@Composable
fun SimpleStyleSamplePreview() = androidx.compose.foundation.samples.SimpleStyleSample()

@Preview
@Composable
fun SimpleVerticalPagerSamplePreview() = androidx.compose.foundation.samples.SimpleVerticalPagerSample()

@Preview
@Composable
fun SimpleWidthModifierPreview() = androidx.compose.foundation.layout.samples.SimpleWidthModifier()

@Preview
@Composable
fun SimpleWrapContentAlignedModifierPreview() = androidx.compose.foundation.layout.samples.SimpleWrapContentAlignedModifier()

@Preview
@Composable
fun SimpleWrapContentHorizontallyAlignedModifierPreview() = androidx.compose.foundation.layout.samples.SimpleWrapContentHorizontallyAlignedModifier()

@Preview
@Composable
fun SimpleWrapContentVerticallyAlignedModifierPreview() = androidx.compose.foundation.layout.samples.SimpleWrapContentVerticallyAlignedModifier()

@Preview
@Composable
fun SnapFlingBehaviorCustomizedSamplePreview() = androidx.compose.foundation.samples.SnapFlingBehaviorCustomizedSample()

@Preview
@Composable
fun SnapFlingBehaviorSimpleSamplePreview() = androidx.compose.foundation.samples.SnapFlingBehaviorSimpleSample()

@Preview
@Composable
fun SnapFlingBehaviorSnapPositionPreview() = androidx.compose.foundation.samples.SnapFlingBehaviorSnapPosition()

@Preview
@Composable
fun SpacerExamplePreview() = androidx.compose.foundation.layout.samples.SpacerExample()

@Preview
@Composable
fun SpecialtyInputsFormSamplePreview() = androidx.compose.foundation.samples.SpecialtyInputsFormSample()

@Preview
@Composable
fun StickyHeaderHeaderIndexSamplePreview() = androidx.compose.foundation.samples.StickyHeaderHeaderIndexSample()

@Preview
@Composable
fun StickyHeaderListSamplePreview() = androidx.compose.foundation.samples.StickyHeaderListSample()

@Preview
@Composable
fun StyleAnimationSamplePreview() = androidx.compose.foundation.samples.StyleAnimationSample()

@Preview
@Composable
fun StyleStateKeySamplePreview() = androidx.compose.foundation.samples.StyleStateKeySample()

@Preview
@Composable
fun StyleStateSamplePreview() = androidx.compose.foundation.samples.StyleStateSample()

@Preview
@Composable
fun SymmetricPaddingModifierPreview() = androidx.compose.foundation.layout.samples.SymmetricPaddingModifier()

@Preview
@Composable
fun TextAutoSizeBasicTextSamplePreview() = androidx.compose.foundation.samples.TextAutoSizeBasicTextSample()

@Preview
@Composable
fun TextFieldStateApplyOutputTransformationPreview() = androidx.compose.foundation.samples.TextFieldStateApplyOutputTransformation()

@Preview
@Composable
fun TextFieldWithIconSamplePreview() = androidx.compose.foundation.samples.TextFieldWithIconSample()

@Preview
@Composable
fun ToggleableSamplePreview() = androidx.compose.foundation.samples.ToggleableSample()

@Preview
@Composable
fun TransformableAnimateBySamplePreview() = androidx.compose.foundation.samples.TransformableAnimateBySample()

@Preview
@Composable
fun TransformableSamplePreview() = androidx.compose.foundation.samples.TransformableSample()

@Preview
@Composable
fun TransformableSampleInsideScrollPreview() = androidx.compose.foundation.samples.TransformableSampleInsideScroll()

@Preview
@Composable
fun TriStateToggleableSamplePreview() = androidx.compose.foundation.samples.TriStateToggleableSample()

@Preview
@Composable
fun UsingListLayoutInfoForSideEffectSamplePreview() = androidx.compose.foundation.samples.UsingListLayoutInfoForSideEffectSample()

@Preview
@Composable
fun UsingListScrollPositionForSideEffectSamplePreview() = androidx.compose.foundation.samples.UsingListScrollPositionForSideEffectSample()

@Preview
@Composable
fun UsingListScrollPositionInCompositionSamplePreview() = androidx.compose.foundation.samples.UsingListScrollPositionInCompositionSample()

@Preview
@Composable
fun UsingPagerLayoutInfoForSideEffectSamplePreview() = androidx.compose.foundation.samples.UsingPagerLayoutInfoForSideEffectSample()

@Preview
@Composable
fun VerticalDragSamplePreview() = androidx.compose.foundation.samples.VerticalDragSample()

@Preview
@Composable
fun VerticalScrollExamplePreview() = androidx.compose.foundation.samples.VerticalScrollExample()

@Preview
@Composable
fun VisibleModifierSamplePreview() = androidx.compose.foundation.layout.samples.VisibleModifierSample()
