package ee.schimke.m3catalog.glimmer

import ee.schimke.composeai.preview.OverrideVariant
import ee.schimke.composeai.preview.VariantInteraction

// GENERATED by scripts/generate-exhaustive-kit-cells.mjs. Edit the real sticker knobs and the
// generator, never this file. These are secondary exact-cell crossings for the imported Figma
// pages; every render still invokes the component named by its catalog sticker.

/**
 * Exact kit cells reachable by crossing
 * glimmer-catalog/src/main/kotlin/ee/schimke/m3catalog/glimmer/Buttons.kt#ToggleButtonSticker.
 */
@OverrideVariant(
  name = "cell-state-enabled-size-large-toggle-true-40000113-4082",
  strings = ["size=Large", "state=checked"],
  kitProps = ["State=Enabled", "Size=Large", "Toggle=True"],
  secondary = true,
)
@OverrideVariant(
  name = "cell-state-focused-size-default-toggle-true-40000113-4092",
  strings = ["state=checked"],
  interaction = VariantInteraction.Focused,
  kitProps = ["State=Focused", "Size=Default", "Toggle=True"],
  secondary = true,
)
@OverrideVariant(
  name = "cell-state-pressed-size-default-toggle-true-40000113-4102",
  strings = ["state=checked"],
  interaction = VariantInteraction.Pressed,
  kitProps = ["State=Pressed", "Size=Default", "Toggle=True"],
  secondary = true,
)
@OverrideVariant(
  name = "cell-state-focused-size-large-toggle-true-40000113-4112",
  strings = ["size=Large", "state=checked"],
  interaction = VariantInteraction.Focused,
  kitProps = ["State=Focused", "Size=Large", "Toggle=True"],
  secondary = true,
)
@OverrideVariant(
  name = "cell-state-pressed-size-large-toggle-true-40000113-4122",
  strings = ["size=Large", "state=checked"],
  interaction = VariantInteraction.Pressed,
  kitProps = ["State=Pressed", "Size=Large", "Toggle=True"],
  secondary = true,
)
annotation class ToggleButtonStickerExhaustiveKitCells

/**
 * Exact kit cells reachable by crossing
 * glimmer-catalog/src/main/kotlin/ee/schimke/m3catalog/glimmer/IconButtons.kt#IconToggleButtonSticker.
 */
@OverrideVariant(
  name = "cell-toggle-true-state-focused-40000113-4188",
  strings = ["state=checked"],
  interaction = VariantInteraction.Focused,
  kitProps = ["Toggle=True", "State=Focused"],
  secondary = true,
)
@OverrideVariant(
  name = "cell-toggle-true-state-pressed-40000113-4195",
  strings = ["state=checked"],
  interaction = VariantInteraction.Pressed,
  kitProps = ["Toggle=True", "State=Pressed"],
  secondary = true,
)
annotation class IconToggleButtonStickerExhaustiveKitCells

/**
 * Exact kit cells reachable by crossing
 * glimmer-catalog/src/main/kotlin/ee/schimke/m3catalog/glimmer/VoiceInput.kt#VoiceInputIndicatorSticker.
 */
@OverrideVariant(
  name = "cell-volume-quiet-contained-yes-40000116-9342",
  strings = ["volume=Quiet", "container=contained"],
  kitProps = ["Volume=Quiet", "Contained=Yes"],
  secondary = true,
)
annotation class VoiceInputIndicatorStickerExhaustiveKitCells
